name: Sandra Haven
favicon: null
layout_spectrum: 0.7606
typography_spectrum: 0.60794
title: Editor and Book Coach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#fefefe'
    - '#7d7d7d'
    - '#fdfe00'
    - '#bc1c21'
  brandStrength: 0.38102178066037595
  lightness: 0.4662263437639922
  saturation: 0.2902231637854129
  rhythmicContrast: 0.3596650529652834
purpose: []
